modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "nichirin"
version = "${version}"
displayName = "Breath of Nichirin: Demon Slayer"
authors = "XircTwerk"
description = '''
Vanilla+ styled demon slayer mod.
'''
#logoFile = ""

[[dependencies.nichirin]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nichirin]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nichirin]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
