# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.5.beta-10
maven_group = com.xirc.nichirin
archives_name = nichirin
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1
yarn_mappings = 1.21.1+build.3
parchment_mappings = 2024.11.17

# MC Dependencies
architectury_api_version = 13.0.8
fabric_loader_version = 0.16.14
fabric_api_version = 0.116.12+1.21.1
neoforge_version = 21.1.233

# Dependencies
azurelib_version = 3.1.8
pal_version = 1.1.4+mc.1.21.1
terrablender_version=4.1.0.8
cloth_config_version=15.0.140