# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.4
maven_group = com.xirc.nichirin
archives_name = nichirin
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.20.1
yarn_mappings = 1.20.1+build.1
parchment_mappings = 2023.09.03

# MC Dependencies
architectury_api_version = 9.2.14
fabric_loader_version = 0.19.2
fabric_api_version = 0.92.9+1.20.1
forge_version = 1.20.1-47.4.10

# Dependencies
azurelib_version = 3.1.10
player_anim_version = 1.0.2-rc1+1.20
terrablender_version=3.0.1.10
cloth_config_version=11.1.136
