architectury {
    common rootProject.enabled_platforms.split(',')
}

sourceSets {
    main {
        resources {
            srcDirs("src/main/generated")
        }
    }
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

loom {
    accessWidenerPath = file("src/main/resources/nichirin.accesswidener")
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"

    compileOnly "mod.azure.azurelib:azurelib-common-1.20.1:${azurelib_version}"

    modImplementation "dev.kosmx.player-anim:player-animation-lib:${rootProject.player_anim_version}"
    modImplementation "dev.kosmx.player-anim:anim-core:${rootProject.player_anim_version}"
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}